inherit_from:
  - .rubocop_airbnb.yml

#rubocopでコード解析したくないファイルやフォルダ
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Max: 137